### PR TITLE
Deploy to repository to Cloudflare pages

### PR DESCRIPTION
**Pull request by Faithtosin**

### CODE REVIEW

**Review by wemeetagain — APPROVED** [review]

**Comment by mpetrunic** [comment]
Think it errors without `--frozen-lockfile` when installing dependencies^^

**Comment by mpetrunic** [comment]
@Faithtosin Let me take a look locally and push fix

**Comment by Faithtosin** [comment]
> @Faithtosin Let me take a look locally and push fix

Looks like node-gyp version needs to be updated.

**Comment by mpetrunic** [comment]
> > @Faithtosin Let me take a look locally and push fix
> 
> Looks like node-gyp version needs to be updated.

I don't think we wan't to compile old node-sass so I bumped deps a bit to a version that has available rebuild binaries (think node-sass is deleting old prebuilt binaries)

**Comment by Faithtosin** [comment]
> > > @Faithtosin Let me take a look locally and push fix
> > 
> > 
> > Looks like node-gyp version needs to be updated.
> 
> I don't think we wan't to compile old node-sass so I bumped deps a bit to a version that has available rebuild binaries (think node-sass is deleting old prebuilt binaries)

Thanks!! It works now.

**Pull request merged**
